apiVersion: v1
kind: Service
metadata:
  name: hello-world-mvn
  labels:
    app: hello-world-mvn
spec:
  type: NodePort #Exposes the service as a node ports
  ports:
  - port: 5000
    name: http
    protocol: TCP
    targetPort: 5000
    nodePort: 30043
  selector:
    app: hello-world-mvn